### ISSUE TITLE
NetIO not working on Server 2022?

### ISSUE THREAD

**Issue by Flashbert** [it-novum/openitcockpit-agent-go#78]
we got two Windows Server 2022. Both with different agents (3.0.10 and 3.0.6)

As soon as we set netio to true in the config.ini, servers answers with "255 out of bounds"

Prüfungskommando | check-host-alive-oitc-agent-pull

# Enable monitoring of the traffic (I/O) of network interfaces
netio = True

If you run the agent-pull-command directly on the server it says following:

`:/opt/openitc/nagios/libexec# /opt/openitc/receiver/bin/poller.php poller -H "fb5f3e06-a483-4907-9886-c86df34eb887" -c /opt/openitc/receiver/etc/production.json --host-check
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string * int in /opt/openitc/receiver/src/itnovum/openITCOCKPIT/Checks/Receiver/Plugins/NetIO.php:136
Stack trace:
#0 /opt/openitc/receiver/src/itnovum/openITCOCKPIT/Checks/Receiver/Plugins/BasePlugin.php(72): itnovum\openITCOCKPIT\Checks\Receiver\Plugins\NetIO->execute()
#1 /opt/openitc/receiver/src/itnovum/openITCOCKPIT/Checks/Receiver/Console/Poller.php(303): itnovum\openITCOCKPIT\Checks\Receiver\Plugins\BasePlugin->__construct()
#2 /opt/openitc/receiver/vendor/symfony/console/Command/Command.php(255): itnovum\openITCOCKPIT\Checks\Receiver\Console\Poller->execute()
#3 /opt/openitc/receiver/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run()
#4 /opt/openitc/receiver/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand()
#5 /opt/openitc/receiver/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /opt/openitc/receiver/bin/poller.php(38): Symfony\Component\Console\Application->run()
#7 {main}
  thrown in /opt/openitc/receiver/src/itnovum/openITCOCKPIT/Checks/Receiver/Plugins/NetIO.php on line 136`

Prüfungskommando	[check-host-alive-oitc-agent-pull](https://192.168.42.242/#!/commands/edit/58)

**Comment by Flashbert** [comment]
Hello,

i removed the services from the host yesterday, today i tried and readded them and the problem is gone.

Info i forgot in the first post: we upgraded from Ubuntu 18 to 22, and also updated oitc to the latest version (due to support drop)
